# Generated by Django 6.0.2 on 2026-02-09 09:16

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hrprofile',
            name='joining_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
