# Generated by Django 6.0.2 on 2026-02-11 06:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0003_hrprofile_account_holder_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hrprofile',
            name='account_holder_name',
        ),
    ]
