# Generated by Django 6.0.2 on 2026-03-05 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0004_remove_hrprofile_account_holder_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='hrprofile',
            name='allowances',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
