import React, { useState, useEffect } from 'react';
import { createPortal } from 'react-dom';
import axios from 'axios';
import API_BASE_URL from '../apiConfig';

const Payslip = () => {
    const [payrolls, setPayrolls] = useState([]);
    const [loading, setLoading] = useState(true);
    const [error, setError] = useState('');
    const [selectedPayroll, setSelectedPayroll] = useState(null);

    const username = localStorage.getItem('username');
    const role = localStorage.getItem('role') || 'EMPLOYEE';
    const themeColor = 'blue';

    useEffect(() => {
        fetchMyPayrolls();
        // eslint-disable-next-line react-hooks/exhaustive-deps
    }, []);

    const fetchMyPayrolls = async () => {
        setLoading(true);
        try {
            const token = localStorage.getItem('token');
            const headers = { Authorization: `Bearer ${token}` };

            // Fetch Users to find accurate name mapping
            let usersList = [];
            try {
                const usersRes = await axios.get(`${API_BASE_URL}/api/accounts/users/admin/`, { headers });
                usersList = Array.isArray(usersRes.data) ? usersRes.data :
                    (usersRes.data && Array.isArray(usersRes.data.results)) ? usersRes.data.results : [];
            } catch (e) { console.error(e); }

            let myName = username;
            const myUserObj = usersList.find(u => u.username === username || u.email === username);
            if (myUserObj) {
                myName = myUserObj.name || username;
            }

            // Fetch Payrolls
            const res = await axios.get(`${API_BASE_URL}/api/payroll/`, { headers });
            let allPayrolls = Array.isArray(res.data) ? res.data :
                (res.data && Array.isArray(res.data.results)) ? res.data.results : [];

            if (role.toUpperCase() === 'ADMIN' || role.toUpperCase() === 'HR') {
                allPayrolls = allPayrolls.filter(p => (p.employee_name && p.employee_name === myName) || String(p.employee) === String(myUserObj?.id));
            }

            setPayrolls(allPayrolls);
            setError('');
        } catch (err) {
            setError('Failed to securely fetch your financial records.');
        } finally {
            setLoading(false);
        }
    };

    const handlePrint = () => {
        window.print();
    };

    if (loading) return (
        <div className="flex flex-col justify-center items-center h-[50vh] gap-4">
            <div className={`w-12 h-12 border-4 border-${themeColor}-600 border-t-transparent rounded-full animate-spin`}></div>
            <p className="text-slate-400 font-bold animate-pulse">Decrypting payroll manifests...</p>
        </div>
    );

    return (
        <div className="max-w-7xl mx-auto pb-12 animate-fadeIn">

            <div className={`bg-gradient-to-r from-${themeColor}-600 to-${themeColor}-800 rounded-3xl p-10 text-white shadow-xl shadow-${themeColor}-900/20 mb-10 relative overflow-hidden`}>
                <div className="absolute top-0 right-0 w-64 h-64 bg-white opacity-5 rounded-full blur-3xl -mr-10 -mt-20"></div>
                <div className="absolute bottom-0 left-10 w-40 h-40 bg-white opacity-5 rounded-full blur-2xl -mb-10"></div>

                <div className="relative z-10">
                    <h1 className="text-4xl font-extrabold tracking-tight mb-2">My Payslips</h1>
                    <p className="text-blue-100 font-medium text-lg max-w-xl">Access and download your official monthly salary slips generated by the system.</p>
                </div>
            </div>

            {error && (
                <div className="mb-8 p-4 bg-red-50 text-red-700 rounded-2xl border border-red-200 text-sm font-bold flex items-center gap-3 animate-shake shadow-sm">
                    <div className="p-1.5 bg-red-100 rounded-lg"><svg className="w-5 h-5" fill="none" viewBox="0 0 24 24" stroke="currentColor"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth="2.5" d="M12 9v2m0 4h.01m-6.938 4h13.856c1.54 0 2.502-1.667 1.732-3L13.732 4c-.77-1.333-2.694-1.333-3.464 0L3.34 16c-.77 1.333.192 3 1.732 3z"></path></svg></div>
                    {error}
                </div>
            )}

            {payrolls.length === 0 ? (
                <div className="bg-white p-16 rounded-[2rem] text-center shadow-[0_8px_30px_rgb(0,0,0,0.04)] border border-slate-100 flex flex-col items-center">
                    <div className={`w-24 h-24 bg-${themeColor}-50 text-${themeColor}-200 rounded-full flex items-center justify-center mb-6 shadow-inner`}>
                        <svg className="w-12 h-12" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M9 12h6m-6 4h6m2 5H7a2 2 0 01-2-2V5a2 2 0 012-2h5.586a1 1 0 01.707.293l5.414 5.414a1 1 0 01.293.707V19a2 2 0 01-2 2z"></path></svg>
                    </div>
                    <h3 className="text-2xl font-extrabold text-slate-800">No Payslips Generated</h3>
                    <p className="text-slate-500 mt-2 font-medium max-w-sm">There are currently no payroll records linked to your account. Check back later after payroll processing.</p>
                </div>
            ) : (
                <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-8">
                    {payrolls.map((payroll, idx) => (
                        <div key={idx} className="bg-white rounded-[2rem] p-8 shadow-[0_8px_30px_rgb(0,0,0,0.04)] border border-slate-100 hover:-translate-y-1 hover:shadow-xl transition-all duration-300 group relative overflow-hidden">
                            {/* Card Accent */}
                            <div className={`absolute top-0 left-0 right-0 h-1.5 bg-gradient-to-r ${payroll.pay === 'PAID' ? 'from-emerald-400 to-emerald-500' : 'from-slate-300 to-slate-400'}`}></div>

                            <div className="flex justify-between items-start mb-8 mt-2">
                                <div className={`bg-${themeColor}-50 text-${themeColor}-700 px-4 py-2 rounded-xl text-sm font-black uppercase tracking-widest border border-${themeColor}-100 shadow-sm`}>
                                    {payroll.month} {payroll.year}
                                </div>
                                <span className={`px-3 py-1.5 text-[10px] font-black uppercase tracking-widest rounded-lg border shadow-sm ${payroll.pay === 'PAID' ? 'bg-emerald-50 text-emerald-700 border-emerald-200' : 'bg-red-50 text-red-700 border-red-200'}`}>
                                    {payroll.pay}
                                </span>
                            </div>

                            <div className="mb-8 p-6 bg-slate-50 rounded-2xl border border-slate-100/50 relative overflow-hidden">
                                <div className="absolute top-0 right-0 p-4 opacity-5"><svg className="w-16 h-16" fill="currentColor" viewBox="0 0 24 24"><path d="M12 2C6.48 2 2 6.48 2 12s4.48 10 10 10 10-4.48 10-10S17.52 2 12 2zm1 15h-2v-2h2v2zm0-4h-2V7h2v6z" /></svg></div>
                                <p className="text-[10px] text-slate-400 font-black uppercase tracking-widest mb-1.5">Net Salary Credited</p>
                                <h3 className="text-4xl font-black text-slate-800 tracking-tight">₹{parseFloat(payroll.total_salary).toLocaleString('en-IN', { minimumFractionDigits: 2 })}</h3>
                            </div>

                            {payroll.pay === 'PAID' ? (
                                <button
                                    onClick={() => setSelectedPayroll(payroll)}
                                    className={`w-full flex items-center justify-center gap-2 bg-white hover:bg-${themeColor}-50 font-black uppercase tracking-widest transition-all text-${themeColor}-600 py-4 rounded-xl border-2 border-${themeColor}-100 hover:border-${themeColor}-200 outline-none shadow-sm active:scale-95 text-xs`}
                                >
                                    <svg className="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth="2.5" d="M15 12a3 3 0 11-6 0 3 3 0 016 0z"></path><path strokeLinecap="round" strokeLinejoin="round" strokeWidth="2.5" d="M2.458 12C3.732 7.943 7.523 5 12 5c4.478 0 8.268 2.943 9.542 7-1.274 4.057-5.064 7-9.542 7-4.477 0-8.268-2.943-9.542-7z"></path></svg>
                                    View Detailed Slip
                                </button>
                            ) : (
                                <div className="w-full flex items-center justify-center gap-2 bg-slate-50 text-slate-400 py-4 rounded-xl border-2 border-dashed border-slate-200 cursor-not-allowed font-bold text-xs uppercase tracking-widest">
                                    <svg className="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth="2.5" d="M12 15v2m-6 4h12a2 2 0 002-2v-6a2 2 0 00-2-2H6a2 2 0 00-2 2v6a2 2 0 00-2 2zm10-10V7a4 4 0 00-8 0v4h8z"></path></svg>
                                    Locked until payout
                                </div>
                            )}
                        </div>
                    ))}
                </div>
            )}

            {/* Print Modal Implementation using Portal */}
            {selectedPayroll && createPortal(
                <div className="fixed inset-0 bg-slate-900/60 backdrop-blur-md flex items-center justify-center p-4 z-[9999] animate-fadeIn overflow-y-auto w-full h-full print:p-0 print:bg-white print:fixed print:inset-0">
                    <div className="bg-white rounded-[2rem] shadow-2xl w-full max-w-4xl flex flex-col relative my-auto print-payslip-area print:shadow-none print:rounded-none overflow-hidden">

                        {/* Top Controls Bar (Hidden in Print) */}
                        <div className="bg-slate-900 p-5 flex justify-between items-center hide-on-print sticky top-0 z-20">
                            <h3 className="text-white font-extrabold tracking-tight flex items-center gap-3">
                                <div className="p-1.5 bg-white/10 rounded-lg"><svg className="w-5 h-5 text-white" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M9 12h6m-6 4h6m2 5H7a2 2 0 01-2-2V5a2 2 0 012-2h5.586a1 1 0 01.707.293l5.414 5.414a1 1 0 01.293.707V19a2 2 0 01-2 2z"></path></svg></div>
                                Official Document Viewer
                            </h3>
                            <div className="flex gap-4">
                                <button
                                    onClick={handlePrint}
                                    className={`flex items-center gap-2 bg-${themeColor}-600 hover:bg-${themeColor}-700 text-white px-6 py-2.5 rounded-xl font-bold text-sm transition shadow-lg shadow-${themeColor}-900/50 active:scale-95`}
                                >
                                    <svg className="w-5 h-5" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth="2.5" d="M17 17h2a2 2 0 002-2v-4a2 2 0 00-2-2H5a2 2 0 00-2 2v4a2 2 0 002 2h2m2 4h6a2 2 0 002-2v-4a2 2 0 00-2-2H9a2 2 0 00-2 2v4a2 2 0 002 2zm8-12V5a2 2 0 00-2-2H9a2 2 0 00-2 2v4h10z"></path></svg>
                                    Print Document
                                </button>
                                <button
                                    onClick={() => setSelectedPayroll(null)}
                                    className="bg-white/10 hover:bg-white/20 text-white w-10 h-10 flex items-center justify-center rounded-xl transition"
                                >
                                    <svg className="w-5 h-5" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth="2.5" d="M6 18L18 6M6 6l12 12"></path></svg>
                                </button>
                            </div>
                        </div>

                        {/* Printable Area */}
                        <div className="p-12 print:p-0 bg-white" id="printable-payslip">

                            {/* Header section */}
                            <div className="flex justify-between items-end border-b-2 border-slate-100 pb-8 mb-10">
                                <div>
                                    <div className={`w-12 h-12 bg-gradient-to-br from-${themeColor}-500 to-${themeColor}-700 rounded-xl mb-4 flex items-center justify-center text-white shadow-lg shadow-${themeColor}-200`}>
                                        <svg className="w-7 h-7" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth="2.5" d="M13 10V3L4 14h7v7l9-11h-7z"></path></svg>
                                    </div>
                                    <h1 className="text-4xl font-black text-slate-800 tracking-tighter">Nexus ERP</h1>
                                    <p className="text-slate-400 mt-1 font-bold tracking-widest uppercase text-xs">Official Remittance Advice</p>
                                </div>
                                <div className="text-right">
                                    <div className={`inline-block bg-${themeColor}-50 text-${themeColor}-800 px-6 py-3 rounded-2xl border border-${themeColor}-100 shadow-sm`}>
                                        <p className={`text-[10px] uppercase font-black tracking-widest text-${themeColor}-500 mb-0.5`}>Disbursement Period</p>
                                        <p className="text-2xl font-black">{selectedPayroll.month} {selectedPayroll.year}</p>
                                    </div>
                                    <p className="text-xs text-slate-400 font-medium mt-3">ID: REF-{selectedPayroll.id || Math.floor(Math.random() * 100000)}</p>
                                </div>
                            </div>

                            {/* Personnel Profile */}
                            <div className="grid grid-cols-2 gap-8 mb-10">
                                <div className="bg-slate-50 p-6 rounded-2xl border border-slate-100 relative overflow-hidden">
                                    <div className={`absolute left-0 top-0 bottom-0 w-1.5 bg-${themeColor}-500`}></div>
                                    <p className="text-[10px] font-black text-slate-400 uppercase tracking-widest mb-1.5">Registered Beneficiary</p>
                                    <p className="text-2xl font-black text-slate-800">{selectedPayroll.employee_name || 'N/A'}</p>
                                </div>
                                <div className="bg-slate-50 p-6 rounded-2xl border border-slate-100 relative overflow-hidden">
                                    <div className={`absolute left-0 top-0 bottom-0 w-1.5 ${selectedPayroll.pay === 'PAID' ? 'bg-emerald-500' : 'bg-red-500'}`}></div>
                                    <p className="text-[10px] font-black text-slate-400 uppercase tracking-widest mb-1.5">Transaction Status</p>
                                    <p className={`text-2xl font-black ${selectedPayroll.pay === 'PAID' ? 'text-emerald-600' : 'text-red-500'}`}>{selectedPayroll.pay}</p>
                                </div>
                            </div>

                            {/* Log */}
                            <h3 className="text-xs font-black text-slate-400 mb-4 tracking-widest uppercase flex items-center gap-2">
                                <span className={`w-6 h-1 bg-${themeColor}-500 rounded-full`}></span> Performance Logs
                            </h3>
                            <div className="grid grid-cols-4 gap-4 mb-10">
                                <div className="border border-slate-100 rounded-2xl p-5 text-center shadow-sm">
                                    <p className="text-[10px] font-black text-slate-400 uppercase tracking-widest mb-2">Total Cycle Period</p>
                                    <p className="text-3xl font-black text-slate-800">{selectedPayroll.total_days}</p>
                                </div>
                                <div className="border border-emerald-100 rounded-2xl p-5 text-center bg-emerald-50 shadow-sm">
                                    <p className="text-[10px] font-black text-emerald-600/60 uppercase tracking-widest mb-2">Active Duties</p>
                                    <p className="text-3xl font-black text-emerald-700">{selectedPayroll.present_days}</p>
                                </div>
                                <div className="border border-amber-100 rounded-2xl p-5 text-center bg-amber-50 shadow-sm">
                                    <p className="text-[10px] font-black text-amber-600/60 uppercase tracking-widest mb-2">Paid Absences</p>
                                    <p className="text-3xl font-black text-amber-700">{selectedPayroll.casual_days}</p>
                                </div>
                                <div className="border border-red-100 rounded-2xl p-5 text-center bg-red-50 shadow-sm">
                                    <p className="text-[10px] font-black text-red-600/60 uppercase tracking-widest mb-2">Unpaid Leave</p>
                                    <p className="text-3xl font-black text-red-700">{selectedPayroll.lop_days}</p>
                                </div>
                            </div>

                            {/* Ledger */}
                            <div className="grid grid-cols-2 gap-10 mb-10">
                                <div className="border border-slate-200 rounded-3xl overflow-hidden shadow-sm">
                                    <div className={`bg-${themeColor}-50/50 border-b border-slate-200 px-6 py-4`}>
                                        <h4 className={`font-black text-${themeColor}-800 uppercase tracking-widest text-[10px]`}>Credits & Earnings</h4>
                                    </div>
                                    <div className="p-6 space-y-5">
                                        <div className="flex justify-between items-center text-sm">
                                            <span className="text-slate-500 font-bold uppercase tracking-wider">Base Remuneration</span>
                                            <span className="font-black text-slate-800 text-lg">₹{parseFloat(selectedPayroll.basic_salary).toLocaleString('en-IN', { minimumFractionDigits: 2 })}</span>
                                        </div>
                                        <div className="flex justify-between items-center text-sm">
                                            <span className="text-slate-500 font-bold uppercase tracking-wider">Variable Allowances</span>
                                            <span className="font-black text-emerald-600 text-lg">₹{parseFloat(selectedPayroll.allowances).toLocaleString('en-IN', { minimumFractionDigits: 2 })}</span>
                                        </div>
                                        <div className="pt-5 border-t-2 border-slate-100 flex justify-between items-center">
                                            <span className="text-[10px] font-black text-slate-400 uppercase tracking-widest">Gross Computed Earnings</span>
                                            <span className="font-black text-slate-900 text-xl">₹{(parseFloat(selectedPayroll.basic_salary) + parseFloat(selectedPayroll.allowances)).toLocaleString('en-IN', { minimumFractionDigits: 2 })}</span>
                                        </div>
                                    </div>
                                </div>

                                <div className="border border-slate-200 rounded-3xl overflow-hidden shadow-sm">
                                    <div className="bg-red-50/50 border-b border-slate-200 px-6 py-4">
                                        <h4 className="font-black text-red-800 uppercase tracking-widest text-[10px]">Debits & Deductions</h4>
                                    </div>
                                    <div className="p-6 space-y-5">
                                        <div className="flex justify-between items-center text-sm">
                                            <span className="text-slate-500 font-bold uppercase tracking-wider">Loss of Pay Adjustments</span>
                                            <span className="font-black text-red-600 text-lg">- ₹{parseFloat(selectedPayroll.deductions).toLocaleString('en-IN', { minimumFractionDigits: 2 })}</span>
                                        </div>
                                        <div className="flex justify-between items-center text-sm text-transparent select-none">
                                            <span>Spacer Element Placeholder</span>
                                            <span className="text-lg">₹0.00</span>
                                        </div>
                                        <div className="pt-5 border-t-2 border-slate-100 flex justify-between items-center">
                                            <span className="text-[10px] font-black text-slate-400 uppercase tracking-widest">Total Sourced Deductions</span>
                                            <span className="font-black text-red-600 text-xl">- ₹{parseFloat(selectedPayroll.deductions).toLocaleString('en-IN', { minimumFractionDigits: 2 })}</span>
                                        </div>
                                    </div>
                                </div>
                            </div>

                            {/* Net total area */}
                            <div className="bg-slate-900 text-white p-10 rounded-3xl flex justify-between items-center shadow-2xl relative overflow-hidden">
                                <div className={`absolute right-0 top-0 bottom-0 w-32 bg-gradient-to-l from-${themeColor}-500/30 to-transparent`}></div>
                                <div className="relative z-10">
                                    <p className="text-[10px] uppercase tracking-widest text-slate-400 font-black mb-1.5">Final Settled Amount</p>
                                    <p className="text-sm text-slate-300 font-bold">Sum routed to registered bank account destination</p>
                                </div>
                                <div className="text-right relative z-10">
                                    <span className="text-white font-black text-5xl tracking-tight">₹{parseFloat(selectedPayroll.total_salary).toLocaleString('en-IN', { minimumFractionDigits: 2 })}</span>
                                </div>
                            </div>

                            <div className="mt-12 pt-8 border-t-2 border-slate-100 flex flex-col items-center justify-center text-center">
                                <p className="text-[10px] text-slate-400 font-black uppercase tracking-widest mb-2 leading-relaxed max-w-lg">
                                    This document is digitally validated by the Nexus ERP system and does not require a physical signature.<br />
                                    For inquiries or discrepancies, file a request through the internal HR portal.
                                </p>
                            </div>
                        </div>
                    </div>
                </div>, document.body
            )}

            <style dangerouslySetInnerHTML={{
                __html: `
                @media print {
                    body { margin: 0 !important; padding: 0 !important; background: #fff !important; }
                    body > * { display: none !important; }
                    .animate-fadeIn, .print-payslip-area {
                        display: block !important; visibility: visible !important;
                        position: relative !important; width: 100% !important;
                        margin: 0 !important; padding: 0 !important;
                        background: white !important; box-shadow: none !important;
                    }
                    .print-payslip-area { padding: 40px !important; }
                    .hide-on-print { display: none !important; }
                    @page { margin: 0.5cm; size: A4; }
                }
            `}} />
        </div>
    );
};

export default Payslip;
