# Generated by Django 6.0.2 on 2026-02-10 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0004_leaverequest_approved_by'),
    ]

    operations = [
        migrations.RenameField(
            model_name='salarystructure',
            old_name='basic',
            new_name='base_salary',
        ),
        migrations.RemoveField(
            model_name='salarystructure',
            name='bonus',
        ),
        migrations.RemoveField(
            model_name='salarystructure',
            name='hra',
        ),
        migrations.AddField(
            model_name='payroll',
            name='allowances',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='payroll',
            name='basic_salary',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='payroll',
            name='deductions',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='salarystructure',
            name='allowances',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='salarystructure',
            name='deductions',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
