# Generated by Django 6.0.2 on 2026-02-10 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0005_rename_basic_salarystructure_base_salary_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaverequest',
            name='leave_type',
            field=models.CharField(choices=[('CASUAL', 'Casual Leave'), ('LOP', 'Loss of Pay')], default='CASUAL', max_length=20),
        ),
        migrations.AddField(
            model_name='payroll',
            name='casual_days',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='payroll',
            name='lop_days',
            field=models.IntegerField(default=0),
        ),
    ]
