# Generated by Django 6.0.2 on 2026-02-10 09:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0006_leaverequest_leave_type_payroll_casual_days_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salarystructure',
            name='deductions',
        ),
        migrations.AlterField(
            model_name='salarystructure',
            name='department',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='employees.department'),
        ),
    ]
