# Generated by Django 6.0.2 on 2026-02-11 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0010_rename_payroll_status_to_pay'),
    ]

    operations = [
        migrations.AddField(
            model_name='payroll',
            name='pay_area',
            field=models.CharField(choices=[('OFFICE', 'Office'), ('FACTORY', 'Factory'), ('WAREHOUSE', 'Warehouse')], default='OFFICE', max_length=20),
        ),
    ]
