# Generated by Django 6.0.2 on 2026-02-11 03:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0011_payroll_pay_area'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payroll',
            name='pay_area',
        ),
    ]
