# Generated by Django 6.0.2 on 2026-02-11 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0012_remove_payroll_pay_area'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payroll',
            name='pay',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('PAID', 'Paid'), ('UNPAID', 'Unpaid')], default='UNPAID', max_length=20),
        ),
    ]
