# Generated by Django 6.0.2 on 2026-02-11 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0014_salarystructure_account_holder_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salarystructure',
            name='account_holder_name',
        ),
        migrations.RemoveField(
            model_name='salarystructure',
            name='account_number',
        ),
        migrations.RemoveField(
            model_name='salarystructure',
            name='bank_name',
        ),
        migrations.RemoveField(
            model_name='salarystructure',
            name='ifsc_code',
        ),
        migrations.AddField(
            model_name='employeeprofile',
            name='account_holder_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='employeeprofile',
            name='account_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='employeeprofile',
            name='bank_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='employeeprofile',
            name='ifsc_code',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
