# Generated by Django 6.0.2 on 2026-02-11 06:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0015_remove_salarystructure_account_holder_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employeeprofile',
            name='account_holder_name',
        ),
    ]
