# Generated by Django 6.0.2 on 2026-03-04 12:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0019_alter_attendance_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendance',
            name='check_in',
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='check_out',
        ),
    ]
