# Generated by Django 6.0.2 on 2026-03-05 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0022_alter_payroll_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeprofile',
            name='allowances',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
