# Generated by Django 6.0.2 on 2026-03-05 12:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0023_employeeprofile_allowances'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SalaryStructure',
        ),
    ]
