# Generated by Django 6.0.2 on 2026-03-06 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0024_delete_salarystructure'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaverequest',
            name='admin_comment',
            field=models.TextField(blank=True, null=True),
        ),
    ]
